services:
  - type: web
    name: background-remover
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.16
    plan: free
    maxMemory: 512
    healthCheckPath: /health